name: Run Docker with aarch64

on:
  workflow_dispatch:

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download mesa and llvm
        run: |
          sudo apt update
          sudo apt install git -y
          git clone https://gitlab.freedesktop.org/mesa/mesa
          cd mesa
          git checkout ed2ec808b1a581cbe875a18e4a3a44e0dcbd26c0
          wget -O 1.patch https://raw.githubusercontent.com/MastaG/mesa-turnip-ppa/e31c35e9c46e510c2445c884da194c51f4eb2abe/turnip-patches/dri3.patch
          git apply -v 1.patch
          cd
          wget llv


      # Set up QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Pull aarch64 Docker image
      - name: Pull aarch64 Docker image
        run: |
          docker pull --platform linux/arm64 ubuntu:latest

      # Run Docker container and execute start.sh
      - name: Run Docker container and execute start.sh
        run: |
          docker run --platform linux/arm64 \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace ubuntu:latest bash start.sh
  
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-artifacts
          path: mesa/build64
