name: test1

on:
  workflow_dispatch:

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Run Docker container and execute start.sh
      - name: Run Docker container and execute start.sh
        run: |
         chmod +x start.sh
         ./start.sh
  
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-artifacts
          path: mesa/build64
