name: Run Docker with aarch64

on:
  workflow_dispatch:

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Download .tar.xz archive
      - name: Download .tar.xz archive
        run: |
          sudo apt update
          sudo apt install wget -y
          wget -L -o archive.tar.xz https://filetransfer.io/data-package/NnGwD5mE/download

      # Extract .tar.xz archive
      - name: Extract .tar.xz archive
        run: |
          mkdir -p extracted
          tar -xJf archive.tar.xz -C extracted

      # Pull aarch64 Docker image
      - name: Pull aarch64 Docker image
        run: |
          docker pull --platform linux/arm64 ubuntu:latest

      # Run Docker container and execute start.sh
      - name: Run Docker container and execute start.sh
        run: |
          docker run --platform linux/arm64 \
            -v ${{ github.workspace }}:/workspace \
            -v ${{ github.workspace }}/extracted/mesa:/root/mesa \
            -w /workspace ubuntu:latest bash start.sh
  
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-artifacts
          path: /extracted/mesa/build64
