name: Run Docker with armhf

on:
  workflow_dispatch:

jobs:
  run-docker:
    runs-on: ubuntu-22.04-arm

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2


      - name: clone git
        run: |
          sudo apt update
          sudo apt install git wget -y
          git clone https://gitlab.freedesktop.org/mesa/mesa.git
          cd mesa
          git checkout a512c2a8b572c5da360873320dbbd343c6223cd6
          wget https://raw.githubusercontent.com/termux-pacman/glibc-packages/4796bfee82b6ec47450e7db82ab12ec9d6dd7c09/gpkg/mesa/wsi-termux-x11-v3.patch
          wget https://raw.githubusercontent.com/MastaG/mesa-turnip-ppa/e31c35e9c46e510c2445c884da194c51f4eb2abe/turnip-patches/fix-for-getprogname.patch
          wget https://raw.githubusercontent.com/MastaG/mesa-turnip-ppa/e31c35e9c46e510c2445c884da194c51f4eb2abe/turnip-patches/fix-for-anon-file.patch
          git apply -v dri3.patch
          git apply -v fix-for-getprogname.patch
          git apply -v fix-for-anon-file.patch

      # Pull armhf Docker image
      - name: Pull armhf Docker image
        run: |
          docker pull --platform linux/arm/v7 ubuntu:22.04

      # Run Docker container and execute start.sh
      - name: Run Docker container and execute start.sh
        run: |
          docker run --platform linux/arm/v7 \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace ubuntu:22.04 bash start.sh
  
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-artifacts
          path: mesa/build64
