name: test1

on:
  workflow_dispatch:

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Pull amd64 Docker image
        run: |
          docker pull --platform linux/amd64 ubuntu:latest


      - name: Run Docker container and execute start.sh
        run: |
          docker run --platform linux/amd64 \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace ubuntu:latest bash start.sh
  
  
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-artifacts
          path: mesa/build64
