name: Run Docker with armhf

on:
  workflow_dispatch:

jobs:
  run-docker:
    runs-on: ubuntu-24.04-arm

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Pull armhf Docker image
      - name: Pull armhf Docker image
        run: |
          docker pull --platform linux/arm/v7 ubuntu:latest

      # Run Docker container and execute start.sh
      - name: Run Docker container and execute start.sh
        run: |
          docker run --platform linux/arm/v7 \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace ubuntu:latest bash start.sh
  
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-artifacts
          path: mesa/build64
