name: Run Docker with aarch64

on:
  workflow_dispatch:

jobs:
  run-docker:
    runs-on: ubuntu-24.04-arm

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Download .tar.xz archive
      - name: Download .tar.xz archive
        run: |
          sudo apt update && sudo apt upgrade
          sudo apt install git

      # Extract .tar.xz archive
      - name: Extract .tar.xz archive
        run: |
          git clone https://gitlab.freedesktop.org/mesa/mesa.git

      
      - name: start.sh
        run: |
          chmod +x start.sh
          ./start.sh

      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-artifacts
          path: mesa/build64
