name: Build Ubuntu ARM64 Chroot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install necessary packages
        run: |
          brew install debootstrap
          sudo mkdir -p /path/to/chroot
          sudo debootstrap --arch=arm64 focal /path/to/chroot http://archive.ubuntu.com/ubuntu/

      - name: Enter chroot and run uname
        run: |
          sudo chroot /path/to/chroot /bin/bash -c 'uname -a'
